import { Component, OnInit} from '@angular/core';
import { ContactsTreeComponent } from './contacts.tree.component';
import { ContactsListService } from '../services/contactslist.service';
@Component({
  selector: 'app-contacts-list',
  templateUrl: './contacts.group.component.html',
  
})
export class ContactsGroupComponent implements OnInit {

//     object1 = [
//     {
//       id: 1,
//       name: '分组1',
//       children: [
//         { id: 2, name: '成员1' },
//         { id: 3, name: '成员2' }
//       ]
//     },
//     {
//       id: 4,
//       name: '分组2',
//       children: [
//         { id: 5, name: '成员3' },
//         {
//           id: 6,
//           name: '分组2.1',
//           children: [
//             { id: 7, name: '成员4' }
//           ]
//         }
//       ]
//     },
//     {
//       id: 8,
//       name: '成员5',
//       children: [
        
//       ]
//     }
//   ];

//   object = [
//         {
//             "id": 74,
//             "name": "办公室",
//             "isdefault": "N",
//             "parentid": 0,
//             "level": 1,
//             "departmentList": null,
//             "corpationMemberList": [
//                 {
//                     "f_basePath": "",
//                     "f_memberid": null,
//                     "f_sitesid": null,
//                     "f_sitessubid": null,
//                     "f_sitesname": null,
//                     "f_sitessubname": null,
//                     "number": 0,
//                     "size": 15,
//                     "start": 0,
//                     "end": 0,
//                     "totalPages": 0,
//                     "totalElements": 0,
//                     "page": 0,
//                     "limit": 0,
//                     "direction": 2,
//                     "id": null,
//                     "memberid": 52,
//                     "corporateid": 31,
//                     "membertype": 0,
//                     "deptname": null,
//                     "deptid": 74,
//                     "email": null,
//                     "letter": "h",
//                     "fullpinyin": "huihui2",
//                     "firstfullpinyin": "hh2",
//                     "headPortrait": "",
//                     "membername": "灰灰2",
//                     "jobmumber": null,
//                     "cellphone": "13801234561",
//                     "applytime": null,
//                     "crmlevel": null,
//                     "companycode": null,
//                     "companyname": null,
//                     "member": null,
//                     "userid": null,
//                     "hxid": null,
//                     "qq": null,
//                     "wechat": null,
//                     "likeMatch": null,
//                     "corporateids": null,
//                     "updatetime": null,
//                     "department": {
//                         "id": 74,
//                         "name": "办公室",
//                         "isdefault": null,
//                         "parentid": 0,
//                         "level": 1,
//                         "departmentList": null,
//                         "corpationMemberList": null,
//                         "corporateid": null,
//                         "createtime": null,
//                         "updatetime": null,
//                         "deleteflag": null
//                     },
//                     "userLabel": null,
//                     "role": null,
//                     "jobname": "测试2",
//                     "userlevel": null,
//                     "organization": null,
//                     "otherdepartment": null,
//                     "parttimejob": null,
//                     "position": "",
//                     "telphone": "",
//                     "memtype": 0
//                 },
//                 {
//                     "f_basePath": "",
//                     "f_memberid": null,
//                     "f_sitesid": null,
//                     "f_sitessubid": null,
//                     "f_sitesname": null,
//                     "f_sitessubname": null,
//                     "number": 0,
//                     "size": 15,
//                     "start": 0,
//                     "end": 0,
//                     "totalPages": 0,
//                     "totalElements": 0,
//                     "page": 0,
//                     "limit": 0,
//                     "direction": 2,
//                     "id": null,
//                     "memberid": 51,
//                     "corporateid": 31,
//                     "membertype": 1,
//                     "deptname": null,
//                     "deptid": 74,
//                     "email": null,
//                     "letter": "c",
//                     "fullpinyin": "paopao",
//                     "firstfullpinyin": "pp",
//                     "headPortrait": "",
//                     "membername": "泡泡",
//                     "jobmumber": null,
//                     "cellphone": "13801234560",
//                     "applytime": null,
//                     "crmlevel": null,
//                     "companycode": null,
//                     "companyname": null,
//                     "member": null,
//                     "userid": null,
//                     "hxid": null,
//                     "qq": null,
//                     "wechat": null,
//                     "likeMatch": null,
//                     "corporateids": null,
//                     "updatetime": null,
//                     "department": {
//                         "id": 74,
//                         "name": "办公室",
//                         "isdefault": null,
//                         "parentid": 0,
//                         "level": 1,
//                         "departmentList": null,
//                         "corpationMemberList": null,
//                         "corporateid": null,
//                         "createtime": null,
//                         "updatetime": null,
//                         "deleteflag": null
//                     },
//                     "userLabel": null,
//                     "role": null,
//                     "jobname": "测试1",
//                     "userlevel": null,
//                     "organization": null,
//                     "otherdepartment": null,
//                     "parttimejob": null,
//                     "position": "",
//                     "telphone": "",
//                     "memtype": 0
//                 }
//             ],
//             "corporateid": 31,
//             "createtime": null,
//             "updatetime": null,
//             "deleteflag": null
//         },
//         {
//             "id": 75,
//             "name": "研发部",
//             "isdefault": "N",
//             "parentid": 0,
//             "level": 1,
//             "departmentList": [
//                 {
//                     "id": 76,
//                     "name": "技术部",
//                     "isdefault": "N",
//                     "parentid": 75,
//                     "level": 1,
//                     "departmentList": null,
//                     "corpationMemberList": [
//                         {
//                             "f_basePath": "",
//                             "f_memberid": null,
//                             "f_sitesid": null,
//                             "f_sitessubid": null,
//                             "f_sitesname": null,
//                             "f_sitessubname": null,
//                             "number": 0,
//                             "size": 15,
//                             "start": 0,
//                             "end": 0,
//                             "totalPages": 0,
//                             "totalElements": 0,
//                             "page": 0,
//                             "limit": 0,
//                             "direction": 2,
//                             "id": null,
//                             "memberid": 56,
//                             "corporateid": 31,
//                             "membertype": 0,
//                             "deptname": null,
//                             "deptid": 76,
//                             "email": null,
//                             "letter": "g",
//                             "fullpinyin": "guanyu",
//                             "firstfullpinyin": "gy",
//                             "headPortrait": "",
//                             "membername": "关羽",
//                             "jobmumber": null,
//                             "cellphone": "13801234564",
//                             "applytime": null,
//                             "crmlevel": null,
//                             "companycode": null,
//                             "companyname": null,
//                             "member": null,
//                             "userid": null,
//                             "hxid": null,
//                             "qq": null,
//                             "wechat": null,
//                             "likeMatch": null,
//                             "corporateids": null,
//                             "updatetime": null,
//                             "department": {
//                                 "id": 76,
//                                 "name": "技术部",
//                                 "isdefault": null,
//                                 "parentid": 75,
//                                 "level": 1,
//                                 "departmentList": null,
//                                 "corpationMemberList": null,
//                                 "corporateid": null,
//                                 "createtime": null,
//                                 "updatetime": null,
//                                 "deleteflag": null
//                             },
//                             "userLabel": null,
//                             "role": null,
//                             "jobname": "测试",
//                             "userlevel": null,
//                             "organization": null,
//                             "otherdepartment": null,
//                             "parttimejob": null,
//                             "position": "",
//                             "telphone": "",
//                             "memtype": 0
//                         },
//                         {
//                             "f_basePath": "",
//                             "f_memberid": null,
//                             "f_sitesid": null,
//                             "f_sitessubid": null,
//                             "f_sitesname": null,
//                             "f_sitessubname": null,
//                             "number": 0,
//                             "size": 15,
//                             "start": 0,
//                             "end": 0,
//                             "totalPages": 0,
//                             "totalElements": 0,
//                             "page": 0,
//                             "limit": 0,
//                             "direction": 2,
//                             "id": null,
//                             "memberid": 57,
//                             "corporateid": 31,
//                             "membertype": 0,
//                             "deptname": null,
//                             "deptid": 76,
//                             "email": null,
//                             "letter": "z",
//                             "fullpinyin": "zhangfei",
//                             "firstfullpinyin": "zf",
//                             "headPortrait": "",
//                             "membername": "张飞",
//                             "jobmumber": null,
//                             "cellphone": "13801234565",
//                             "applytime": null,
//                             "crmlevel": null,
//                             "companycode": null,
//                             "companyname": null,
//                             "member": null,
//                             "userid": null,
//                             "hxid": null,
//                             "qq": null,
//                             "wechat": null,
//                             "likeMatch": null,
//                             "corporateids": null,
//                             "updatetime": null,
//                             "department": {
//                                 "id": 76,
//                                 "name": "技术部",
//                                 "isdefault": null,
//                                 "parentid": 75,
//                                 "level": 1,
//                                 "departmentList": null,
//                                 "corpationMemberList": null,
//                                 "corporateid": null,
//                                 "createtime": null,
//                                 "updatetime": null,
//                                 "deleteflag": null
//                             },
//                             "userLabel": null,
//                             "role": null,
//                             "jobname": "测试",
//                             "userlevel": null,
//                             "organization": null,
//                             "otherdepartment": null,
//                             "parttimejob": null,
//                             "position": "",
//                             "telphone": "",
//                             "memtype": 0
//                         }
//                     ],
//                     "corporateid": 31,
//                     "createtime": null,
//                     "updatetime": null,
//                     "deleteflag": null
//                 },
//                 {
//                     "id": 77,
//                     "name": "产品部",
//                     "isdefault": "N",
//                     "parentid": 75,
//                     "level": 1,
//                     "departmentList": [
//                         {
//                             "id": 78,
//                             "name": "产品一组",
//                             "isdefault": "N",
//                             "parentid": 77,
//                             "level": 1,
//                             "departmentList": null,
//                             "corpationMemberList": [
//                                 {
//                                     "f_basePath": "",
//                                     "f_memberid": null,
//                                     "f_sitesid": null,
//                                     "f_sitessubid": null,
//                                     "f_sitesname": null,
//                                     "f_sitessubname": null,
//                                     "number": 0,
//                                     "size": 15,
//                                     "start": 0,
//                                     "end": 0,
//                                     "totalPages": 0,
//                                     "totalElements": 0,
//                                     "page": 0,
//                                     "limit": 0,
//                                     "direction": 2,
//                                     "id": null,
//                                     "memberid": 62,
//                                     "corporateid": 31,
//                                     "membertype": 0,
//                                     "deptname": null,
//                                     "deptid": 78,
//                                     "email": null,
//                                     "letter": "g",
//                                     "fullpinyin": "guojia2",
//                                     "firstfullpinyin": "gj2",
//                                     "headPortrait": "",
//                                     "membername": "郭嘉2",
//                                     "jobmumber": null,
//                                     "cellphone": "13801234569",
//                                     "applytime": null,
//                                     "crmlevel": null,
//                                     "companycode": null,
//                                     "companyname": null,
//                                     "member": null,
//                                     "userid": null,
//                                     "hxid": null,
//                                     "qq": null,
//                                     "wechat": null,
//                                     "likeMatch": null,
//                                     "corporateids": null,
//                                     "updatetime": null,
//                                     "department": {
//                                         "id": 78,
//                                         "name": "产品一组",
//                                         "isdefault": null,
//                                         "parentid": 77,
//                                         "level": 1,
//                                         "departmentList": null,
//                                         "corpationMemberList": null,
//                                         "corporateid": null,
//                                         "createtime": null,
//                                         "updatetime": null,
//                                         "deleteflag": null
//                                     },
//                                     "userLabel": null,
//                                     "role": null,
//                                     "jobname": "测试",
//                                     "userlevel": null,
//                                     "organization": null,
//                                     "otherdepartment": null,
//                                     "parttimejob": null,
//                                     "position": "",
//                                     "telphone": "",
//                                     "memtype": 0
//                                 },
//                                 {
//                                     "f_basePath": "",
//                                     "f_memberid": null,
//                                     "f_sitesid": null,
//                                     "f_sitessubid": null,
//                                     "f_sitesname": null,
//                                     "f_sitessubname": null,
//                                     "number": 0,
//                                     "size": 15,
//                                     "start": 0,
//                                     "end": 0,
//                                     "totalPages": 0,
//                                     "totalElements": 0,
//                                     "page": 0,
//                                     "limit": 0,
//                                     "direction": 2,
//                                     "id": null,
//                                     "memberid": 61,
//                                     "corporateid": 31,
//                                     "membertype": 0,
//                                     "deptname": null,
//                                     "deptid": 78,
//                                     "email": null,
//                                     "letter": "z",
//                                     "fullpinyin": "zhangcan3",
//                                     "firstfullpinyin": "zc3",
//                                     "headPortrait": "",
//                                     "membername": "张灿3",
//                                     "jobmumber": null,
//                                     "cellphone": "13801234568",
//                                     "applytime": null,
//                                     "crmlevel": null,
//                                     "companycode": null,
//                                     "companyname": null,
//                                     "member": null,
//                                     "userid": null,
//                                     "hxid": null,
//                                     "qq": null,
//                                     "wechat": null,
//                                     "likeMatch": null,
//                                     "corporateids": null,
//                                     "updatetime": null,
//                                     "department": {
//                                         "id": 78,
//                                         "name": "产品一组",
//                                         "isdefault": null,
//                                         "parentid": 77,
//                                         "level": 1,
//                                         "departmentList": null,
//                                         "corpationMemberList": null,
//                                         "corporateid": null,
//                                         "createtime": null,
//                                         "updatetime": null,
//                                         "deleteflag": null
//                                     },
//                                     "userLabel": null,
//                                     "role": null,
//                                     "jobname": "测试",
//                                     "userlevel": null,
//                                     "organization": null,
//                                     "otherdepartment": null,
//                                     "parttimejob": null,
//                                     "position": "",
//                                     "telphone": "",
//                                     "memtype": 0
//                                 }
//                             ],
//                             "corporateid": 31,
//                             "createtime": null,
//                             "updatetime": null,
//                             "deleteflag": null
//                         }
//                     ],
//                     "corpationMemberList": [
//                         {
//                             "f_basePath": "",
//                             "f_memberid": null,
//                             "f_sitesid": null,
//                             "f_sitessubid": null,
//                             "f_sitesname": null,
//                             "f_sitessubname": null,
//                             "number": 0,
//                             "size": 15,
//                             "start": 0,
//                             "end": 0,
//                             "totalPages": 0,
//                             "totalElements": 0,
//                             "page": 0,
//                             "limit": 0,
//                             "direction": 2,
//                             "id": null,
//                             "memberid": 59,
//                             "corporateid": 31,
//                             "membertype": 0,
//                             "deptname": null,
//                             "deptid": 77,
//                             "email": null,
//                             "letter": "z",
//                             "fullpinyin": "zhangjiao",
//                             "firstfullpinyin": "zj",
//                             "headPortrait": "",
//                             "membername": "张角",
//                             "jobmumber": null,
//                             "cellphone": "13801234566",
//                             "applytime": null,
//                             "crmlevel": null,
//                             "companycode": null,
//                             "companyname": null,
//                             "member": null,
//                             "userid": null,
//                             "hxid": null,
//                             "qq": null,
//                             "wechat": null,
//                             "likeMatch": null,
//                             "corporateids": null,
//                             "updatetime": null,
//                             "department": {
//                                 "id": 77,
//                                 "name": "产品部",
//                                 "isdefault": null,
//                                 "parentid": 75,
//                                 "level": 1,
//                                 "departmentList": null,
//                                 "corpationMemberList": null,
//                                 "corporateid": null,
//                                 "createtime": null,
//                                 "updatetime": null,
//                                 "deleteflag": null
//                             },
//                             "userLabel": null,
//                             "role": null,
//                             "jobname": "测试",
//                             "userlevel": null,
//                             "organization": null,
//                             "otherdepartment": null,
//                             "parttimejob": null,
//                             "position": "",
//                             "telphone": "",
//                             "memtype": 0
//                         },
//                         {
//                             "f_basePath": "",
//                             "f_memberid": null,
//                             "f_sitesid": null,
//                             "f_sitessubid": null,
//                             "f_sitesname": null,
//                             "f_sitessubname": null,
//                             "number": 0,
//                             "size": 15,
//                             "start": 0,
//                             "end": 0,
//                             "totalPages": 0,
//                             "totalElements": 0,
//                             "page": 0,
//                             "limit": 0,
//                             "direction": 2,
//                             "id": null,
//                             "memberid": 60,
//                             "corporateid": 31,
//                             "membertype": 0,
//                             "deptname": null,
//                             "deptid": 77,
//                             "email": null,
//                             "letter": "z",
//                             "fullpinyin": "zhanghafeng",
//                             "firstfullpinyin": "zhf",
//                             "headPortrait": "",
//                             "membername": "张哈风",
//                             "jobmumber": null,
//                             "cellphone": "13801234567",
//                             "applytime": null,
//                             "crmlevel": null,
//                             "companycode": null,
//                             "companyname": null,
//                             "member": null,
//                             "userid": null,
//                             "hxid": null,
//                             "qq": null,
//                             "wechat": null,
//                             "likeMatch": null,
//                             "corporateids": null,
//                             "updatetime": null,
//                             "department": {
//                                 "id": 77,
//                                 "name": "产品部",
//                                 "isdefault": null,
//                                 "parentid": 75,
//                                 "level": 1,
//                                 "departmentList": null,
//                                 "corpationMemberList": null,
//                                 "corporateid": null,
//                                 "createtime": null,
//                                 "updatetime": null,
//                                 "deleteflag": null
//                             },
//                             "userLabel": null,
//                             "role": null,
//                             "jobname": "测试",
//                             "userlevel": null,
//                             "organization": null,
//                             "otherdepartment": null,
//                             "parttimejob": null,
//                             "position": "",
//                             "telphone": "",
//                             "memtype": 0
//                         }
//                     ],
//                     "corporateid": 31,
//                     "createtime": null,
//                     "updatetime": null,
//                     "deleteflag": null
//                 }
//             ],
//             "corpationMemberList": [
//                 {
//                     "f_basePath": "",
//                     "f_memberid": null,
//                     "f_sitesid": null,
//                     "f_sitessubid": null,
//                     "f_sitesname": null,
//                     "f_sitessubname": null,
//                     "number": 0,
//                     "size": 15,
//                     "start": 0,
//                     "end": 0,
//                     "totalPages": 0,
//                     "totalElements": 0,
//                     "page": 0,
//                     "limit": 0,
//                     "direction": 2,
//                     "id": null,
//                     "memberid": 54,
//                     "corporateid": 31,
//                     "membertype": 0,
//                     "deptname": null,
//                     "deptid": 75,
//                     "email": null,
//                     "letter": "s",
//                     "fullpinyin": "zhangcan2",
//                     "firstfullpinyin": "zc2",
//                     "headPortrait": "",
//                     "membername": "张灿2",
//                     "jobmumber": null,
//                     "cellphone": "13801234562",
//                     "applytime": null,
//                     "crmlevel": null,
//                     "companycode": null,
//                     "companyname": null,
//                     "member": null,
//                     "userid": null,
//                     "hxid": null,
//                     "qq": null,
//                     "wechat": null,
//                     "likeMatch": null,
//                     "corporateids": null,
//                     "updatetime": null,
//                     "department": {
//                         "id": 75,
//                         "name": "研发部",
//                         "isdefault": null,
//                         "parentid": 0,
//                         "level": 1,
//                         "departmentList": null,
//                         "corpationMemberList": null,
//                         "corporateid": null,
//                         "createtime": null,
//                         "updatetime": null,
//                         "deleteflag": null
//                     },
//                     "userLabel": null,
//                     "role": null,
//                     "jobname": "老大",
//                     "userlevel": null,
//                     "organization": null,
//                     "otherdepartment": null,
//                     "parttimejob": null,
//                     "position": "",
//                     "telphone": "",
//                     "memtype": 0
//                 },
//                 {
//                     "f_basePath": "",
//                     "f_memberid": null,
//                     "f_sitesid": null,
//                     "f_sitessubid": null,
//                     "f_sitesname": null,
//                     "f_sitessubname": null,
//                     "number": 0,
//                     "size": 15,
//                     "start": 0,
//                     "end": 0,
//                     "totalPages": 0,
//                     "totalElements": 0,
//                     "page": 0,
//                     "limit": 0,
//                     "direction": 2,
//                     "id": null,
//                     "memberid": 55,
//                     "corporateid": 31,
//                     "membertype": 0,
//                     "deptname": null,
//                     "deptid": 75,
//                     "email": null,
//                     "letter": "z",
//                     "fullpinyin": "zhaoyun",
//                     "firstfullpinyin": "zy",
//                     "headPortrait": "",
//                     "membername": "赵云",
//                     "jobmumber": null,
//                     "cellphone": "13801234563",
//                     "applytime": null,
//                     "crmlevel": null,
//                     "companycode": null,
//                     "companyname": null,
//                     "member": null,
//                     "userid": null,
//                     "hxid": null,
//                     "qq": null,
//                     "wechat": null,
//                     "likeMatch": null,
//                     "corporateids": null,
//                     "updatetime": null,
//                     "department": {
//                         "id": 75,
//                         "name": "研发部",
//                         "isdefault": null,
//                         "parentid": 0,
//                         "level": 1,
//                         "departmentList": null,
//                         "corpationMemberList": null,
//                         "corporateid": null,
//                         "createtime": null,
//                         "updatetime": null,
//                         "deleteflag": null
//                     },
//                     "userLabel": null,
//                     "role": null,
//                     "jobname": "测试",
//                     "userlevel": null,
//                     "organization": null,
//                     "otherdepartment": null,
//                     "parttimejob": null,
//                     "position": "",
//                     "telphone": "",
//                     "memtype": 0
//                 }
//             ],
//             "corporateid": 31,
//             "createtime": null,
//             "updatetime": null,
//             "deleteflag": null
//         }
//     ];
    object: any =[];
    selectedContacts : any;
  	constructor(public contactslistService: ContactsListService
    ) {

    }

    ngOnInit() : void {
        this.loadData('');
        this.contactslistService.updateSelectedContacts.subscribe(
            ()=>{
                this.selectedContacts = this.contactslistService.selectedContacts;
            }
        )
        
    }

    public loadData(searchText:string){
  		return this.contactslistService.getGroupList(searchText).subscribe(
  			res=>{
  				// this.contacts = res["data"];
                this.object = res["data"];
  			},
  			error => {console.log(error)},
  			() => {}
  		);
  	}
    countChange ($event) {
        this.selectedContacts = $event;
        console.log($event);
    }
    onSelect(contacts: any) : void {
      this.selectedContacts = contacts;
    }


}
